scale = 0.15
res = 1200
pre_onset_aggr = 0.0
post_onset_aggr = 0.3
onset_prob = 0.005
particle_roughness = 0.05
particle_min_len = 0.01
particle_max_len = 0.8
particle_min_intensity = 0.5
particle_max_intensity = 1.5
accel_distr_mu = 0.0
accel_distr_sig = 0.1
raccel_distr_mu = 0.0
raccel_distr_sig = 0.3
drag_coeff = 0.1
bounce_strength = 0.001
particle_cnt = 200
num_ptypes = 100
frame_cnt = 5
fps = 60
video_cnt = 2
